// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/notifications/notifications.proto

package notifications

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Notification Types
type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNSPECIFIED NotificationType = 0
	// System notifications
	NotificationType_NOTIFICATION_TYPE_SYSTEM_ALERT   NotificationType = 1
	NotificationType_NOTIFICATION_TYPE_SERVER_DOWN    NotificationType = 2
	NotificationType_NOTIFICATION_TYPE_SERVER_UP      NotificationType = 3
	NotificationType_NOTIFICATION_TYPE_HIGH_LOAD      NotificationType = 4
	NotificationType_NOTIFICATION_TYPE_LOW_DISK_SPACE NotificationType = 5
	NotificationType_NOTIFICATION_TYPE_BACKUP_FAILED  NotificationType = 6
	NotificationType_NOTIFICATION_TYPE_BACKUP_SUCCESS NotificationType = 7
	NotificationType_NOTIFICATION_TYPE_UPDATE_FAILED  NotificationType = 8
	NotificationType_NOTIFICATION_TYPE_UPDATE_SUCCESS NotificationType = 9
	// User notifications
	NotificationType_NOTIFICATION_TYPE_USER_LOGIN           NotificationType = 10
	NotificationType_NOTIFICATION_TYPE_USER_LOGOUT          NotificationType = 11
	NotificationType_NOTIFICATION_TYPE_USER_REGISTERED      NotificationType = 12
	NotificationType_NOTIFICATION_TYPE_USER_BLOCKED         NotificationType = 13
	NotificationType_NOTIFICATION_TYPE_USER_UNBLOCKED       NotificationType = 14
	NotificationType_NOTIFICATION_TYPE_PASSWORD_RESET       NotificationType = 15
	NotificationType_NOTIFICATION_TYPE_SUBSCRIPTION_EXPIRED NotificationType = 16
	NotificationType_NOTIFICATION_TYPE_SUBSCRIPTION_RENEWED NotificationType = 17
	// VPN notifications
	NotificationType_NOTIFICATION_TYPE_VPN_CONNECTED    NotificationType = 18
	NotificationType_NOTIFICATION_TYPE_VPN_DISCONNECTED NotificationType = 19
	NotificationType_NOTIFICATION_TYPE_VPN_ERROR        NotificationType = 20
	NotificationType_NOTIFICATION_TYPE_BYPASS_BLOCKED   NotificationType = 21
	NotificationType_NOTIFICATION_TYPE_BYPASS_SUCCESS   NotificationType = 22
	// Analytics notifications
	NotificationType_NOTIFICATION_TYPE_METRICS_ALERT      NotificationType = 23
	NotificationType_NOTIFICATION_TYPE_ANOMALY_DETECTED   NotificationType = 24
	NotificationType_NOTIFICATION_TYPE_THRESHOLD_EXCEEDED NotificationType = 25
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0:  "NOTIFICATION_TYPE_UNSPECIFIED",
		1:  "NOTIFICATION_TYPE_SYSTEM_ALERT",
		2:  "NOTIFICATION_TYPE_SERVER_DOWN",
		3:  "NOTIFICATION_TYPE_SERVER_UP",
		4:  "NOTIFICATION_TYPE_HIGH_LOAD",
		5:  "NOTIFICATION_TYPE_LOW_DISK_SPACE",
		6:  "NOTIFICATION_TYPE_BACKUP_FAILED",
		7:  "NOTIFICATION_TYPE_BACKUP_SUCCESS",
		8:  "NOTIFICATION_TYPE_UPDATE_FAILED",
		9:  "NOTIFICATION_TYPE_UPDATE_SUCCESS",
		10: "NOTIFICATION_TYPE_USER_LOGIN",
		11: "NOTIFICATION_TYPE_USER_LOGOUT",
		12: "NOTIFICATION_TYPE_USER_REGISTERED",
		13: "NOTIFICATION_TYPE_USER_BLOCKED",
		14: "NOTIFICATION_TYPE_USER_UNBLOCKED",
		15: "NOTIFICATION_TYPE_PASSWORD_RESET",
		16: "NOTIFICATION_TYPE_SUBSCRIPTION_EXPIRED",
		17: "NOTIFICATION_TYPE_SUBSCRIPTION_RENEWED",
		18: "NOTIFICATION_TYPE_VPN_CONNECTED",
		19: "NOTIFICATION_TYPE_VPN_DISCONNECTED",
		20: "NOTIFICATION_TYPE_VPN_ERROR",
		21: "NOTIFICATION_TYPE_BYPASS_BLOCKED",
		22: "NOTIFICATION_TYPE_BYPASS_SUCCESS",
		23: "NOTIFICATION_TYPE_METRICS_ALERT",
		24: "NOTIFICATION_TYPE_ANOMALY_DETECTED",
		25: "NOTIFICATION_TYPE_THRESHOLD_EXCEEDED",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNSPECIFIED":          0,
		"NOTIFICATION_TYPE_SYSTEM_ALERT":         1,
		"NOTIFICATION_TYPE_SERVER_DOWN":          2,
		"NOTIFICATION_TYPE_SERVER_UP":            3,
		"NOTIFICATION_TYPE_HIGH_LOAD":            4,
		"NOTIFICATION_TYPE_LOW_DISK_SPACE":       5,
		"NOTIFICATION_TYPE_BACKUP_FAILED":        6,
		"NOTIFICATION_TYPE_BACKUP_SUCCESS":       7,
		"NOTIFICATION_TYPE_UPDATE_FAILED":        8,
		"NOTIFICATION_TYPE_UPDATE_SUCCESS":       9,
		"NOTIFICATION_TYPE_USER_LOGIN":           10,
		"NOTIFICATION_TYPE_USER_LOGOUT":          11,
		"NOTIFICATION_TYPE_USER_REGISTERED":      12,
		"NOTIFICATION_TYPE_USER_BLOCKED":         13,
		"NOTIFICATION_TYPE_USER_UNBLOCKED":       14,
		"NOTIFICATION_TYPE_PASSWORD_RESET":       15,
		"NOTIFICATION_TYPE_SUBSCRIPTION_EXPIRED": 16,
		"NOTIFICATION_TYPE_SUBSCRIPTION_RENEWED": 17,
		"NOTIFICATION_TYPE_VPN_CONNECTED":        18,
		"NOTIFICATION_TYPE_VPN_DISCONNECTED":     19,
		"NOTIFICATION_TYPE_VPN_ERROR":            20,
		"NOTIFICATION_TYPE_BYPASS_BLOCKED":       21,
		"NOTIFICATION_TYPE_BYPASS_SUCCESS":       22,
		"NOTIFICATION_TYPE_METRICS_ALERT":        23,
		"NOTIFICATION_TYPE_ANOMALY_DETECTED":     24,
		"NOTIFICATION_TYPE_THRESHOLD_EXCEEDED":   25,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_notifications_notifications_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_api_proto_notifications_notifications_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{0}
}

type NotificationPriority int32

const (
	NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED NotificationPriority = 0
	NotificationPriority_NOTIFICATION_PRIORITY_LOW         NotificationPriority = 1
	NotificationPriority_NOTIFICATION_PRIORITY_NORMAL      NotificationPriority = 2
	NotificationPriority_NOTIFICATION_PRIORITY_HIGH        NotificationPriority = 3
	NotificationPriority_NOTIFICATION_PRIORITY_URGENT      NotificationPriority = 4
)

// Enum value maps for NotificationPriority.
var (
	NotificationPriority_name = map[int32]string{
		0: "NOTIFICATION_PRIORITY_UNSPECIFIED",
		1: "NOTIFICATION_PRIORITY_LOW",
		2: "NOTIFICATION_PRIORITY_NORMAL",
		3: "NOTIFICATION_PRIORITY_HIGH",
		4: "NOTIFICATION_PRIORITY_URGENT",
	}
	NotificationPriority_value = map[string]int32{
		"NOTIFICATION_PRIORITY_UNSPECIFIED": 0,
		"NOTIFICATION_PRIORITY_LOW":         1,
		"NOTIFICATION_PRIORITY_NORMAL":      2,
		"NOTIFICATION_PRIORITY_HIGH":        3,
		"NOTIFICATION_PRIORITY_URGENT":      4,
	}
)

func (x NotificationPriority) Enum() *NotificationPriority {
	p := new(NotificationPriority)
	*p = x
	return p
}

func (x NotificationPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_notifications_notifications_proto_enumTypes[1].Descriptor()
}

func (NotificationPriority) Type() protoreflect.EnumType {
	return &file_api_proto_notifications_notifications_proto_enumTypes[1]
}

func (x NotificationPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationPriority.Descriptor instead.
func (NotificationPriority) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{1}
}

type NotificationChannel int32

const (
	NotificationChannel_NOTIFICATION_CHANNEL_UNSPECIFIED NotificationChannel = 0
	NotificationChannel_NOTIFICATION_CHANNEL_EMAIL       NotificationChannel = 1
	NotificationChannel_NOTIFICATION_CHANNEL_SMS         NotificationChannel = 2
	NotificationChannel_NOTIFICATION_CHANNEL_PUSH        NotificationChannel = 3
	NotificationChannel_NOTIFICATION_CHANNEL_TELEGRAM    NotificationChannel = 4
	NotificationChannel_NOTIFICATION_CHANNEL_WEBHOOK     NotificationChannel = 5
	NotificationChannel_NOTIFICATION_CHANNEL_SLACK       NotificationChannel = 6
)

// Enum value maps for NotificationChannel.
var (
	NotificationChannel_name = map[int32]string{
		0: "NOTIFICATION_CHANNEL_UNSPECIFIED",
		1: "NOTIFICATION_CHANNEL_EMAIL",
		2: "NOTIFICATION_CHANNEL_SMS",
		3: "NOTIFICATION_CHANNEL_PUSH",
		4: "NOTIFICATION_CHANNEL_TELEGRAM",
		5: "NOTIFICATION_CHANNEL_WEBHOOK",
		6: "NOTIFICATION_CHANNEL_SLACK",
	}
	NotificationChannel_value = map[string]int32{
		"NOTIFICATION_CHANNEL_UNSPECIFIED": 0,
		"NOTIFICATION_CHANNEL_EMAIL":       1,
		"NOTIFICATION_CHANNEL_SMS":         2,
		"NOTIFICATION_CHANNEL_PUSH":        3,
		"NOTIFICATION_CHANNEL_TELEGRAM":    4,
		"NOTIFICATION_CHANNEL_WEBHOOK":     5,
		"NOTIFICATION_CHANNEL_SLACK":       6,
	}
)

func (x NotificationChannel) Enum() *NotificationChannel {
	p := new(NotificationChannel)
	*p = x
	return p
}

func (x NotificationChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_notifications_notifications_proto_enumTypes[2].Descriptor()
}

func (NotificationChannel) Type() protoreflect.EnumType {
	return &file_api_proto_notifications_notifications_proto_enumTypes[2]
}

func (x NotificationChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationChannel.Descriptor instead.
func (NotificationChannel) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{2}
}

type NotificationStatus int32

const (
	NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED NotificationStatus = 0
	NotificationStatus_NOTIFICATION_STATUS_PENDING     NotificationStatus = 1
	NotificationStatus_NOTIFICATION_STATUS_SENDING     NotificationStatus = 2
	NotificationStatus_NOTIFICATION_STATUS_SENT        NotificationStatus = 3
	NotificationStatus_NOTIFICATION_STATUS_DELIVERED   NotificationStatus = 4
	NotificationStatus_NOTIFICATION_STATUS_FAILED      NotificationStatus = 5
	NotificationStatus_NOTIFICATION_STATUS_CANCELLED   NotificationStatus = 6
)

// Enum value maps for NotificationStatus.
var (
	NotificationStatus_name = map[int32]string{
		0: "NOTIFICATION_STATUS_UNSPECIFIED",
		1: "NOTIFICATION_STATUS_PENDING",
		2: "NOTIFICATION_STATUS_SENDING",
		3: "NOTIFICATION_STATUS_SENT",
		4: "NOTIFICATION_STATUS_DELIVERED",
		5: "NOTIFICATION_STATUS_FAILED",
		6: "NOTIFICATION_STATUS_CANCELLED",
	}
	NotificationStatus_value = map[string]int32{
		"NOTIFICATION_STATUS_UNSPECIFIED": 0,
		"NOTIFICATION_STATUS_PENDING":     1,
		"NOTIFICATION_STATUS_SENDING":     2,
		"NOTIFICATION_STATUS_SENT":        3,
		"NOTIFICATION_STATUS_DELIVERED":   4,
		"NOTIFICATION_STATUS_FAILED":      5,
		"NOTIFICATION_STATUS_CANCELLED":   6,
	}
)

func (x NotificationStatus) Enum() *NotificationStatus {
	p := new(NotificationStatus)
	*p = x
	return p
}

func (x NotificationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_notifications_notifications_proto_enumTypes[3].Descriptor()
}

func (NotificationStatus) Type() protoreflect.EnumType {
	return &file_api_proto_notifications_notifications_proto_enumTypes[3]
}

func (x NotificationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationStatus.Descriptor instead.
func (NotificationStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{3}
}

// Health
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Main Notification message
type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          NotificationType       `protobuf:"varint,2,opt,name=type,proto3,enum=notifications.NotificationType" json:"type,omitempty"`
	Priority      NotificationPriority   `protobuf:"varint,3,opt,name=priority,proto3,enum=notifications.NotificationPriority" json:"priority,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Data          map[string]string      `protobuf:"bytes,6,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Channels      []NotificationChannel  `protobuf:"varint,7,rep,packed,name=channels,proto3,enum=notifications.NotificationChannel" json:"channels,omitempty"`
	Recipients    []string               `protobuf:"bytes,8,rep,name=recipients,proto3" json:"recipients,omitempty"`
	Source        string                 `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	SourceId      string                 `protobuf:"bytes,10,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Status        NotificationStatus     `protobuf:"varint,11,opt,name=status,proto3,enum=notifications.NotificationStatus" json:"status,omitempty"`
	Attempts      int32                  `protobuf:"varint,12,opt,name=attempts,proto3" json:"attempts,omitempty"`
	MaxAttempts   int32                  `protobuf:"varint,13,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	Error         string                 `protobuf:"bytes,18,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{2}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *Notification) GetPriority() NotificationPriority {
	if x != nil {
		return x.Priority
	}
	return NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Notification) GetChannels() []NotificationChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *Notification) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *Notification) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Notification) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Notification) GetStatus() NotificationStatus {
	if x != nil {
		return x.Status
	}
	return NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED
}

func (x *Notification) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *Notification) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Notification) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Notification) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *Notification) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *Notification) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Notification Template
type NotificationTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          NotificationType       `protobuf:"varint,2,opt,name=type,proto3,enum=notifications.NotificationType" json:"type,omitempty"`
	Priority      NotificationPriority   `protobuf:"varint,3,opt,name=priority,proto3,enum=notifications.NotificationPriority" json:"priority,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Channels      []NotificationChannel  `protobuf:"varint,6,rep,packed,name=channels,proto3,enum=notifications.NotificationChannel" json:"channels,omitempty"`
	Enabled       bool                   `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationTemplate) Reset() {
	*x = NotificationTemplate{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationTemplate) ProtoMessage() {}

func (x *NotificationTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationTemplate.ProtoReflect.Descriptor instead.
func (*NotificationTemplate) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{3}
}

func (x *NotificationTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotificationTemplate) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *NotificationTemplate) GetPriority() NotificationPriority {
	if x != nil {
		return x.Priority
	}
	return NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED
}

func (x *NotificationTemplate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationTemplate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotificationTemplate) GetChannels() []NotificationChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *NotificationTemplate) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *NotificationTemplate) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NotificationTemplate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Notification Preference
type NotificationPreference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          NotificationType       `protobuf:"varint,2,opt,name=type,proto3,enum=notifications.NotificationType" json:"type,omitempty"`
	Channels      []NotificationChannel  `protobuf:"varint,3,rep,packed,name=channels,proto3,enum=notifications.NotificationChannel" json:"channels,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Schedule      *NotificationSchedule  `protobuf:"bytes,5,opt,name=schedule,proto3" json:"schedule,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationPreference) Reset() {
	*x = NotificationPreference{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationPreference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationPreference) ProtoMessage() {}

func (x *NotificationPreference) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationPreference.ProtoReflect.Descriptor instead.
func (*NotificationPreference) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{4}
}

func (x *NotificationPreference) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotificationPreference) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *NotificationPreference) GetChannels() []NotificationChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *NotificationPreference) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *NotificationPreference) GetSchedule() *NotificationSchedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *NotificationPreference) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NotificationPreference) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Notification Schedule
type NotificationSchedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     string                 `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // HH:MM
	EndTime       string                 `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // HH:MM
	Timezone      string                 `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Days          []int32                `protobuf:"varint,4,rep,packed,name=days,proto3" json:"days,omitempty"` // 0=Sunday, 1=Monday, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationSchedule) Reset() {
	*x = NotificationSchedule{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationSchedule) ProtoMessage() {}

func (x *NotificationSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationSchedule.ProtoReflect.Descriptor instead.
func (*NotificationSchedule) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{5}
}

func (x *NotificationSchedule) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *NotificationSchedule) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *NotificationSchedule) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *NotificationSchedule) GetDays() []int32 {
	if x != nil {
		return x.Days
	}
	return nil
}

// Notification Stats
type NotificationStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalSent     int64                  `protobuf:"varint,1,opt,name=total_sent,json=totalSent,proto3" json:"total_sent,omitempty"`
	TotalFailed   int64                  `protobuf:"varint,2,opt,name=total_failed,json=totalFailed,proto3" json:"total_failed,omitempty"`
	TotalPending  int64                  `protobuf:"varint,3,opt,name=total_pending,json=totalPending,proto3" json:"total_pending,omitempty"`
	ByType        map[string]int64       `protobuf:"bytes,4,rep,name=by_type,json=byType,proto3" json:"by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ByChannel     map[string]int64       `protobuf:"bytes,5,rep,name=by_channel,json=byChannel,proto3" json:"by_channel,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ByPriority    map[string]int64       `protobuf:"bytes,6,rep,name=by_priority,json=byPriority,proto3" json:"by_priority,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	SuccessRate   float64                `protobuf:"fixed64,7,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	AverageDelay  float64                `protobuf:"fixed64,8,opt,name=average_delay,json=averageDelay,proto3" json:"average_delay,omitempty"` // in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationStats) Reset() {
	*x = NotificationStats{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationStats) ProtoMessage() {}

func (x *NotificationStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationStats.ProtoReflect.Descriptor instead.
func (*NotificationStats) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{6}
}

func (x *NotificationStats) GetTotalSent() int64 {
	if x != nil {
		return x.TotalSent
	}
	return 0
}

func (x *NotificationStats) GetTotalFailed() int64 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

func (x *NotificationStats) GetTotalPending() int64 {
	if x != nil {
		return x.TotalPending
	}
	return 0
}

func (x *NotificationStats) GetByType() map[string]int64 {
	if x != nil {
		return x.ByType
	}
	return nil
}

func (x *NotificationStats) GetByChannel() map[string]int64 {
	if x != nil {
		return x.ByChannel
	}
	return nil
}

func (x *NotificationStats) GetByPriority() map[string]int64 {
	if x != nil {
		return x.ByPriority
	}
	return nil
}

func (x *NotificationStats) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *NotificationStats) GetAverageDelay() float64 {
	if x != nil {
		return x.AverageDelay
	}
	return 0
}

// Request/Response messages
type DispatchNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          NotificationType       `protobuf:"varint,2,opt,name=type,proto3,enum=notifications.NotificationType" json:"type,omitempty"`
	Priority      NotificationPriority   `protobuf:"varint,3,opt,name=priority,proto3,enum=notifications.NotificationPriority" json:"priority,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Data          map[string]string      `protobuf:"bytes,6,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Channels      []NotificationChannel  `protobuf:"varint,7,rep,packed,name=channels,proto3,enum=notifications.NotificationChannel" json:"channels,omitempty"`
	Recipients    []string               `protobuf:"bytes,8,rep,name=recipients,proto3" json:"recipients,omitempty"`
	Source        string                 `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	SourceId      string                 `protobuf:"bytes,10,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	MaxAttempts   int32                  `protobuf:"varint,11,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchNotificationRequest) Reset() {
	*x = DispatchNotificationRequest{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchNotificationRequest) ProtoMessage() {}

func (x *DispatchNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchNotificationRequest.ProtoReflect.Descriptor instead.
func (*DispatchNotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{7}
}

func (x *DispatchNotificationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DispatchNotificationRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *DispatchNotificationRequest) GetPriority() NotificationPriority {
	if x != nil {
		return x.Priority
	}
	return NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED
}

func (x *DispatchNotificationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DispatchNotificationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DispatchNotificationRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DispatchNotificationRequest) GetChannels() []NotificationChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *DispatchNotificationRequest) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *DispatchNotificationRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DispatchNotificationRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *DispatchNotificationRequest) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *DispatchNotificationRequest) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

type DispatchNotificationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NotificationId string                 `protobuf:"bytes,3,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DispatchNotificationResponse) Reset() {
	*x = DispatchNotificationResponse{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchNotificationResponse) ProtoMessage() {}

func (x *DispatchNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchNotificationResponse.ProtoReflect.Descriptor instead.
func (*DispatchNotificationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{8}
}

func (x *DispatchNotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DispatchNotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DispatchNotificationResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type GetNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationRequest) Reset() {
	*x = GetNotificationRequest{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationRequest) ProtoMessage() {}

func (x *GetNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{9}
}

func (x *GetNotificationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipient     string                 `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Type          NotificationType       `protobuf:"varint,2,opt,name=type,proto3,enum=notifications.NotificationType" json:"type,omitempty"`
	Status        NotificationStatus     `protobuf:"varint,3,opt,name=status,proto3,enum=notifications.NotificationStatus" json:"status,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Limit         int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{10}
}

func (x *ListNotificationsRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *ListNotificationsRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *ListNotificationsRequest) GetStatus() NotificationStatus {
	if x != nil {
		return x.Status
	}
	return NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED
}

func (x *ListNotificationsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ListNotificationsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListNotificationsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ListNotificationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListNotificationsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{11}
}

func (x *ListNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ListNotificationsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateNotificationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        NotificationStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=notifications.NotificationStatus" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationStatusRequest) Reset() {
	*x = UpdateNotificationStatusRequest{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationStatusRequest) ProtoMessage() {}

func (x *UpdateNotificationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateNotificationStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateNotificationStatusRequest) GetStatus() NotificationStatus {
	if x != nil {
		return x.Status
	}
	return NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED
}

func (x *UpdateNotificationStatusRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpdateNotificationStatusRequest) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

type CreateTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          NotificationType       `protobuf:"varint,1,opt,name=type,proto3,enum=notifications.NotificationType" json:"type,omitempty"`
	Priority      NotificationPriority   `protobuf:"varint,2,opt,name=priority,proto3,enum=notifications.NotificationPriority" json:"priority,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Channels      []NotificationChannel  `protobuf:"varint,5,rep,packed,name=channels,proto3,enum=notifications.NotificationChannel" json:"channels,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateRequest) Reset() {
	*x = CreateTemplateRequest{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateRequest) ProtoMessage() {}

func (x *CreateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{13}
}

func (x *CreateTemplateRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *CreateTemplateRequest) GetPriority() NotificationPriority {
	if x != nil {
		return x.Priority
	}
	return NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED
}

func (x *CreateTemplateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTemplateRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateTemplateRequest) GetChannels() []NotificationChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *CreateTemplateRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type GetTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateRequest) Reset() {
	*x = GetTemplateRequest{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateRequest) ProtoMessage() {}

func (x *GetTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{14}
}

func (x *GetTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          NotificationType       `protobuf:"varint,1,opt,name=type,proto3,enum=notifications.NotificationType" json:"type,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{15}
}

func (x *ListTemplatesRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *ListTemplatesRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ListTemplatesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTemplatesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTemplatesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Templates     []*NotificationTemplate `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	Total         int32                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{16}
}

func (x *ListTemplatesResponse) GetTemplates() []*NotificationTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *ListTemplatesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          NotificationType       `protobuf:"varint,2,opt,name=type,proto3,enum=notifications.NotificationType" json:"type,omitempty"`
	Priority      NotificationPriority   `protobuf:"varint,3,opt,name=priority,proto3,enum=notifications.NotificationPriority" json:"priority,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Channels      []NotificationChannel  `protobuf:"varint,6,rep,packed,name=channels,proto3,enum=notifications.NotificationChannel" json:"channels,omitempty"`
	Enabled       bool                   `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateRequest) Reset() {
	*x = UpdateTemplateRequest{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateRequest) ProtoMessage() {}

func (x *UpdateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTemplateRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *UpdateTemplateRequest) GetPriority() NotificationPriority {
	if x != nil {
		return x.Priority
	}
	return NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED
}

func (x *UpdateTemplateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateTemplateRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateTemplateRequest) GetChannels() []NotificationChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *UpdateTemplateRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type DeleteTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateRequest) Reset() {
	*x = DeleteTemplateRequest{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateRequest) ProtoMessage() {}

func (x *DeleteTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateResponse) Reset() {
	*x = DeleteTemplateResponse{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateResponse) ProtoMessage() {}

func (x *DeleteTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateResponse.ProtoReflect.Descriptor instead.
func (*DeleteTemplateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteTemplateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUserPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          NotificationType       `protobuf:"varint,2,opt,name=type,proto3,enum=notifications.NotificationType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPreferencesRequest) Reset() {
	*x = GetUserPreferencesRequest{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPreferencesRequest) ProtoMessage() {}

func (x *GetUserPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetUserPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{20}
}

func (x *GetUserPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserPreferencesRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

type UpdateUserPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          NotificationType       `protobuf:"varint,2,opt,name=type,proto3,enum=notifications.NotificationType" json:"type,omitempty"`
	Channels      []NotificationChannel  `protobuf:"varint,3,rep,packed,name=channels,proto3,enum=notifications.NotificationChannel" json:"channels,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Schedule      *NotificationSchedule  `protobuf:"bytes,5,opt,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPreferencesRequest) Reset() {
	*x = UpdateUserPreferencesRequest{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPreferencesRequest) ProtoMessage() {}

func (x *UpdateUserPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateUserPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserPreferencesRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *UpdateUserPreferencesRequest) GetChannels() []NotificationChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *UpdateUserPreferencesRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UpdateUserPreferencesRequest) GetSchedule() *NotificationSchedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

type GetNotificationStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Type          NotificationType       `protobuf:"varint,4,opt,name=type,proto3,enum=notifications.NotificationType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationStatsRequest) Reset() {
	*x = GetNotificationStatsRequest{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationStatsRequest) ProtoMessage() {}

func (x *GetNotificationStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationStatsRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{22}
}

func (x *GetNotificationStatsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetNotificationStatsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetNotificationStatsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetNotificationStatsRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

var File_api_proto_notifications_notifications_proto protoreflect.FileDescriptor

const file_api_proto_notifications_notifications_proto_rawDesc = "" +
	"\n" +
	"+api/proto/notifications/notifications.proto\x12\rnotifications\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0f\n" +
	"\rHealthRequest\"|\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xc7\x06\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.notifications.NotificationTypeR\x04type\x12?\n" +
	"\bpriority\x18\x03 \x01(\x0e2#.notifications.NotificationPriorityR\bpriority\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x129\n" +
	"\x04data\x18\x06 \x03(\v2%.notifications.Notification.DataEntryR\x04data\x12>\n" +
	"\bchannels\x18\a \x03(\x0e2\".notifications.NotificationChannelR\bchannels\x12\x1e\n" +
	"\n" +
	"recipients\x18\b \x03(\tR\n" +
	"recipients\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\x12\x1b\n" +
	"\tsource_id\x18\n" +
	" \x01(\tR\bsourceId\x129\n" +
	"\x06status\x18\v \x01(\x0e2!.notifications.NotificationStatusR\x06status\x12\x1a\n" +
	"\battempts\x18\f \x01(\x05R\battempts\x12!\n" +
	"\fmax_attempts\x18\r \x01(\x05R\vmaxAttempts\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\fscheduled_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x123\n" +
	"\asent_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12\x14\n" +
	"\x05error\x18\x12 \x01(\tR\x05error\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x03\n" +
	"\x14NotificationTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.notifications.NotificationTypeR\x04type\x12?\n" +
	"\bpriority\x18\x03 \x01(\x0e2#.notifications.NotificationPriorityR\bpriority\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12>\n" +
	"\bchannels\x18\x06 \x03(\x0e2\".notifications.NotificationChannelR\bchannels\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf7\x02\n" +
	"\x16NotificationPreference\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.notifications.NotificationTypeR\x04type\x12>\n" +
	"\bchannels\x18\x03 \x03(\x0e2\".notifications.NotificationChannelR\bchannels\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12?\n" +
	"\bschedule\x18\x05 \x01(\v2#.notifications.NotificationScheduleR\bschedule\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x80\x01\n" +
	"\x14NotificationSchedule\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\tR\aendTime\x12\x1a\n" +
	"\btimezone\x18\x03 \x01(\tR\btimezone\x12\x12\n" +
	"\x04days\x18\x04 \x03(\x05R\x04days\"\xe4\x04\n" +
	"\x11NotificationStats\x12\x1d\n" +
	"\n" +
	"total_sent\x18\x01 \x01(\x03R\ttotalSent\x12!\n" +
	"\ftotal_failed\x18\x02 \x01(\x03R\vtotalFailed\x12#\n" +
	"\rtotal_pending\x18\x03 \x01(\x03R\ftotalPending\x12E\n" +
	"\aby_type\x18\x04 \x03(\v2,.notifications.NotificationStats.ByTypeEntryR\x06byType\x12N\n" +
	"\n" +
	"by_channel\x18\x05 \x03(\v2/.notifications.NotificationStats.ByChannelEntryR\tbyChannel\x12Q\n" +
	"\vby_priority\x18\x06 \x03(\v20.notifications.NotificationStats.ByPriorityEntryR\n" +
	"byPriority\x12!\n" +
	"\fsuccess_rate\x18\a \x01(\x01R\vsuccessRate\x12#\n" +
	"\raverage_delay\x18\b \x01(\x01R\faverageDelay\x1a9\n" +
	"\vByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a<\n" +
	"\x0eByChannelEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a=\n" +
	"\x0fByPriorityEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xcd\x04\n" +
	"\x1bDispatchNotificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.notifications.NotificationTypeR\x04type\x12?\n" +
	"\bpriority\x18\x03 \x01(\x0e2#.notifications.NotificationPriorityR\bpriority\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12H\n" +
	"\x04data\x18\x06 \x03(\v24.notifications.DispatchNotificationRequest.DataEntryR\x04data\x12>\n" +
	"\bchannels\x18\a \x03(\x0e2\".notifications.NotificationChannelR\bchannels\x12\x1e\n" +
	"\n" +
	"recipients\x18\b \x03(\tR\n" +
	"recipients\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\x12\x1b\n" +
	"\tsource_id\x18\n" +
	" \x01(\tR\bsourceId\x12!\n" +
	"\fmax_attempts\x18\v \x01(\x05R\vmaxAttempts\x12=\n" +
	"\fscheduled_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"\x1cDispatchNotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fnotification_id\x18\x03 \x01(\tR\x0enotificationId\"(\n" +
	"\x16GetNotificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xe0\x02\n" +
	"\x18ListNotificationsRequest\x12\x1c\n" +
	"\trecipient\x18\x01 \x01(\tR\trecipient\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.notifications.NotificationTypeR\x04type\x129\n" +
	"\x06status\x18\x03 \x01(\x0e2!.notifications.NotificationStatusR\x06status\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\b \x01(\x05R\x06offset\"t\n" +
	"\x19ListNotificationsResponse\x12A\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1b.notifications.NotificationR\rnotifications\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xb7\x01\n" +
	"\x1fUpdateNotificationStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.notifications.NotificationStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x123\n" +
	"\asent_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"\x97\x02\n" +
	"\x15CreateTemplateRequest\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.notifications.NotificationTypeR\x04type\x12?\n" +
	"\bpriority\x18\x02 \x01(\x0e2#.notifications.NotificationPriorityR\bpriority\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12>\n" +
	"\bchannels\x18\x05 \x03(\x0e2\".notifications.NotificationChannelR\bchannels\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\"$\n" +
	"\x12GetTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x93\x01\n" +
	"\x14ListTemplatesRequest\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.notifications.NotificationTypeR\x04type\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"p\n" +
	"\x15ListTemplatesResponse\x12A\n" +
	"\ttemplates\x18\x01 \x03(\v2#.notifications.NotificationTemplateR\ttemplates\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xa7\x02\n" +
	"\x15UpdateTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.notifications.NotificationTypeR\x04type\x12?\n" +
	"\bpriority\x18\x03 \x01(\x0e2#.notifications.NotificationPriorityR\bpriority\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12>\n" +
	"\bchannels\x18\x06 \x03(\x0e2\".notifications.NotificationChannelR\bchannels\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\"'\n" +
	"\x15DeleteTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteTemplateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"i\n" +
	"\x19GetUserPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.notifications.NotificationTypeR\x04type\"\x87\x02\n" +
	"\x1cUpdateUserPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.notifications.NotificationTypeR\x04type\x12>\n" +
	"\bchannels\x18\x03 \x03(\x0e2\".notifications.NotificationChannelR\bchannels\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12?\n" +
	"\bschedule\x18\x05 \x01(\v2#.notifications.NotificationScheduleR\bschedule\"\xdc\x01\n" +
	"\x1bGetNotificationStatsRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x123\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1f.notifications.NotificationTypeR\x04type*\xdf\a\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eNOTIFICATION_TYPE_SYSTEM_ALERT\x10\x01\x12!\n" +
	"\x1dNOTIFICATION_TYPE_SERVER_DOWN\x10\x02\x12\x1f\n" +
	"\x1bNOTIFICATION_TYPE_SERVER_UP\x10\x03\x12\x1f\n" +
	"\x1bNOTIFICATION_TYPE_HIGH_LOAD\x10\x04\x12$\n" +
	" NOTIFICATION_TYPE_LOW_DISK_SPACE\x10\x05\x12#\n" +
	"\x1fNOTIFICATION_TYPE_BACKUP_FAILED\x10\x06\x12$\n" +
	" NOTIFICATION_TYPE_BACKUP_SUCCESS\x10\a\x12#\n" +
	"\x1fNOTIFICATION_TYPE_UPDATE_FAILED\x10\b\x12$\n" +
	" NOTIFICATION_TYPE_UPDATE_SUCCESS\x10\t\x12 \n" +
	"\x1cNOTIFICATION_TYPE_USER_LOGIN\x10\n" +
	"\x12!\n" +
	"\x1dNOTIFICATION_TYPE_USER_LOGOUT\x10\v\x12%\n" +
	"!NOTIFICATION_TYPE_USER_REGISTERED\x10\f\x12\"\n" +
	"\x1eNOTIFICATION_TYPE_USER_BLOCKED\x10\r\x12$\n" +
	" NOTIFICATION_TYPE_USER_UNBLOCKED\x10\x0e\x12$\n" +
	" NOTIFICATION_TYPE_PASSWORD_RESET\x10\x0f\x12*\n" +
	"&NOTIFICATION_TYPE_SUBSCRIPTION_EXPIRED\x10\x10\x12*\n" +
	"&NOTIFICATION_TYPE_SUBSCRIPTION_RENEWED\x10\x11\x12#\n" +
	"\x1fNOTIFICATION_TYPE_VPN_CONNECTED\x10\x12\x12&\n" +
	"\"NOTIFICATION_TYPE_VPN_DISCONNECTED\x10\x13\x12\x1f\n" +
	"\x1bNOTIFICATION_TYPE_VPN_ERROR\x10\x14\x12$\n" +
	" NOTIFICATION_TYPE_BYPASS_BLOCKED\x10\x15\x12$\n" +
	" NOTIFICATION_TYPE_BYPASS_SUCCESS\x10\x16\x12#\n" +
	"\x1fNOTIFICATION_TYPE_METRICS_ALERT\x10\x17\x12&\n" +
	"\"NOTIFICATION_TYPE_ANOMALY_DETECTED\x10\x18\x12(\n" +
	"$NOTIFICATION_TYPE_THRESHOLD_EXCEEDED\x10\x19*\xc0\x01\n" +
	"\x14NotificationPriority\x12%\n" +
	"!NOTIFICATION_PRIORITY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19NOTIFICATION_PRIORITY_LOW\x10\x01\x12 \n" +
	"\x1cNOTIFICATION_PRIORITY_NORMAL\x10\x02\x12\x1e\n" +
	"\x1aNOTIFICATION_PRIORITY_HIGH\x10\x03\x12 \n" +
	"\x1cNOTIFICATION_PRIORITY_URGENT\x10\x04*\xfd\x01\n" +
	"\x13NotificationChannel\x12$\n" +
	" NOTIFICATION_CHANNEL_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aNOTIFICATION_CHANNEL_EMAIL\x10\x01\x12\x1c\n" +
	"\x18NOTIFICATION_CHANNEL_SMS\x10\x02\x12\x1d\n" +
	"\x19NOTIFICATION_CHANNEL_PUSH\x10\x03\x12!\n" +
	"\x1dNOTIFICATION_CHANNEL_TELEGRAM\x10\x04\x12 \n" +
	"\x1cNOTIFICATION_CHANNEL_WEBHOOK\x10\x05\x12\x1e\n" +
	"\x1aNOTIFICATION_CHANNEL_SLACK\x10\x06*\xff\x01\n" +
	"\x12NotificationStatus\x12#\n" +
	"\x1fNOTIFICATION_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bNOTIFICATION_STATUS_PENDING\x10\x01\x12\x1f\n" +
	"\x1bNOTIFICATION_STATUS_SENDING\x10\x02\x12\x1c\n" +
	"\x18NOTIFICATION_STATUS_SENT\x10\x03\x12!\n" +
	"\x1dNOTIFICATION_STATUS_DELIVERED\x10\x04\x12\x1e\n" +
	"\x1aNOTIFICATION_STATUS_FAILED\x10\x05\x12!\n" +
	"\x1dNOTIFICATION_STATUS_CANCELLED\x10\x062\xfc\t\n" +
	"\x14NotificationsService\x12E\n" +
	"\x06Health\x12\x1c.notifications.HealthRequest\x1a\x1d.notifications.HealthResponse\x12o\n" +
	"\x14DispatchNotification\x12*.notifications.DispatchNotificationRequest\x1a+.notifications.DispatchNotificationResponse\x12U\n" +
	"\x0fGetNotification\x12%.notifications.GetNotificationRequest\x1a\x1b.notifications.Notification\x12f\n" +
	"\x11ListNotifications\x12'.notifications.ListNotificationsRequest\x1a(.notifications.ListNotificationsResponse\x12g\n" +
	"\x18UpdateNotificationStatus\x12..notifications.UpdateNotificationStatusRequest\x1a\x1b.notifications.Notification\x12[\n" +
	"\x0eCreateTemplate\x12$.notifications.CreateTemplateRequest\x1a#.notifications.NotificationTemplate\x12U\n" +
	"\vGetTemplate\x12!.notifications.GetTemplateRequest\x1a#.notifications.NotificationTemplate\x12Z\n" +
	"\rListTemplates\x12#.notifications.ListTemplatesRequest\x1a$.notifications.ListTemplatesResponse\x12[\n" +
	"\x0eUpdateTemplate\x12$.notifications.UpdateTemplateRequest\x1a#.notifications.NotificationTemplate\x12]\n" +
	"\x0eDeleteTemplate\x12$.notifications.DeleteTemplateRequest\x1a%.notifications.DeleteTemplateResponse\x12e\n" +
	"\x12GetUserPreferences\x12(.notifications.GetUserPreferencesRequest\x1a%.notifications.NotificationPreference\x12k\n" +
	"\x15UpdateUserPreferences\x12+.notifications.UpdateUserPreferencesRequest\x1a%.notifications.NotificationPreference\x12d\n" +
	"\x14GetNotificationStats\x12*.notifications.GetNotificationStatsRequest\x1a .notifications.NotificationStatsB@Z>github.com/par1ram/silence/api/gateway/api/proto/notificationsb\x06proto3"

var (
	file_api_proto_notifications_notifications_proto_rawDescOnce sync.Once
	file_api_proto_notifications_notifications_proto_rawDescData []byte
)

func file_api_proto_notifications_notifications_proto_rawDescGZIP() []byte {
	file_api_proto_notifications_notifications_proto_rawDescOnce.Do(func() {
		file_api_proto_notifications_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_notifications_notifications_proto_rawDesc), len(file_api_proto_notifications_notifications_proto_rawDesc)))
	})
	return file_api_proto_notifications_notifications_proto_rawDescData
}

var file_api_proto_notifications_notifications_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_proto_notifications_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_api_proto_notifications_notifications_proto_goTypes = []any{
	(NotificationType)(0),                   // 0: notifications.NotificationType
	(NotificationPriority)(0),               // 1: notifications.NotificationPriority
	(NotificationChannel)(0),                // 2: notifications.NotificationChannel
	(NotificationStatus)(0),                 // 3: notifications.NotificationStatus
	(*HealthRequest)(nil),                   // 4: notifications.HealthRequest
	(*HealthResponse)(nil),                  // 5: notifications.HealthResponse
	(*Notification)(nil),                    // 6: notifications.Notification
	(*NotificationTemplate)(nil),            // 7: notifications.NotificationTemplate
	(*NotificationPreference)(nil),          // 8: notifications.NotificationPreference
	(*NotificationSchedule)(nil),            // 9: notifications.NotificationSchedule
	(*NotificationStats)(nil),               // 10: notifications.NotificationStats
	(*DispatchNotificationRequest)(nil),     // 11: notifications.DispatchNotificationRequest
	(*DispatchNotificationResponse)(nil),    // 12: notifications.DispatchNotificationResponse
	(*GetNotificationRequest)(nil),          // 13: notifications.GetNotificationRequest
	(*ListNotificationsRequest)(nil),        // 14: notifications.ListNotificationsRequest
	(*ListNotificationsResponse)(nil),       // 15: notifications.ListNotificationsResponse
	(*UpdateNotificationStatusRequest)(nil), // 16: notifications.UpdateNotificationStatusRequest
	(*CreateTemplateRequest)(nil),           // 17: notifications.CreateTemplateRequest
	(*GetTemplateRequest)(nil),              // 18: notifications.GetTemplateRequest
	(*ListTemplatesRequest)(nil),            // 19: notifications.ListTemplatesRequest
	(*ListTemplatesResponse)(nil),           // 20: notifications.ListTemplatesResponse
	(*UpdateTemplateRequest)(nil),           // 21: notifications.UpdateTemplateRequest
	(*DeleteTemplateRequest)(nil),           // 22: notifications.DeleteTemplateRequest
	(*DeleteTemplateResponse)(nil),          // 23: notifications.DeleteTemplateResponse
	(*GetUserPreferencesRequest)(nil),       // 24: notifications.GetUserPreferencesRequest
	(*UpdateUserPreferencesRequest)(nil),    // 25: notifications.UpdateUserPreferencesRequest
	(*GetNotificationStatsRequest)(nil),     // 26: notifications.GetNotificationStatsRequest
	nil,                                     // 27: notifications.Notification.DataEntry
	nil,                                     // 28: notifications.NotificationStats.ByTypeEntry
	nil,                                     // 29: notifications.NotificationStats.ByChannelEntry
	nil,                                     // 30: notifications.NotificationStats.ByPriorityEntry
	nil,                                     // 31: notifications.DispatchNotificationRequest.DataEntry
	(*timestamppb.Timestamp)(nil),           // 32: google.protobuf.Timestamp
}
var file_api_proto_notifications_notifications_proto_depIdxs = []int32{
	32, // 0: notifications.HealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: notifications.Notification.type:type_name -> notifications.NotificationType
	1,  // 2: notifications.Notification.priority:type_name -> notifications.NotificationPriority
	27, // 3: notifications.Notification.data:type_name -> notifications.Notification.DataEntry
	2,  // 4: notifications.Notification.channels:type_name -> notifications.NotificationChannel
	3,  // 5: notifications.Notification.status:type_name -> notifications.NotificationStatus
	32, // 6: notifications.Notification.created_at:type_name -> google.protobuf.Timestamp
	32, // 7: notifications.Notification.updated_at:type_name -> google.protobuf.Timestamp
	32, // 8: notifications.Notification.scheduled_at:type_name -> google.protobuf.Timestamp
	32, // 9: notifications.Notification.sent_at:type_name -> google.protobuf.Timestamp
	0,  // 10: notifications.NotificationTemplate.type:type_name -> notifications.NotificationType
	1,  // 11: notifications.NotificationTemplate.priority:type_name -> notifications.NotificationPriority
	2,  // 12: notifications.NotificationTemplate.channels:type_name -> notifications.NotificationChannel
	32, // 13: notifications.NotificationTemplate.created_at:type_name -> google.protobuf.Timestamp
	32, // 14: notifications.NotificationTemplate.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 15: notifications.NotificationPreference.type:type_name -> notifications.NotificationType
	2,  // 16: notifications.NotificationPreference.channels:type_name -> notifications.NotificationChannel
	9,  // 17: notifications.NotificationPreference.schedule:type_name -> notifications.NotificationSchedule
	32, // 18: notifications.NotificationPreference.created_at:type_name -> google.protobuf.Timestamp
	32, // 19: notifications.NotificationPreference.updated_at:type_name -> google.protobuf.Timestamp
	28, // 20: notifications.NotificationStats.by_type:type_name -> notifications.NotificationStats.ByTypeEntry
	29, // 21: notifications.NotificationStats.by_channel:type_name -> notifications.NotificationStats.ByChannelEntry
	30, // 22: notifications.NotificationStats.by_priority:type_name -> notifications.NotificationStats.ByPriorityEntry
	0,  // 23: notifications.DispatchNotificationRequest.type:type_name -> notifications.NotificationType
	1,  // 24: notifications.DispatchNotificationRequest.priority:type_name -> notifications.NotificationPriority
	31, // 25: notifications.DispatchNotificationRequest.data:type_name -> notifications.DispatchNotificationRequest.DataEntry
	2,  // 26: notifications.DispatchNotificationRequest.channels:type_name -> notifications.NotificationChannel
	32, // 27: notifications.DispatchNotificationRequest.scheduled_at:type_name -> google.protobuf.Timestamp
	0,  // 28: notifications.ListNotificationsRequest.type:type_name -> notifications.NotificationType
	3,  // 29: notifications.ListNotificationsRequest.status:type_name -> notifications.NotificationStatus
	32, // 30: notifications.ListNotificationsRequest.start_time:type_name -> google.protobuf.Timestamp
	32, // 31: notifications.ListNotificationsRequest.end_time:type_name -> google.protobuf.Timestamp
	6,  // 32: notifications.ListNotificationsResponse.notifications:type_name -> notifications.Notification
	3,  // 33: notifications.UpdateNotificationStatusRequest.status:type_name -> notifications.NotificationStatus
	32, // 34: notifications.UpdateNotificationStatusRequest.sent_at:type_name -> google.protobuf.Timestamp
	0,  // 35: notifications.CreateTemplateRequest.type:type_name -> notifications.NotificationType
	1,  // 36: notifications.CreateTemplateRequest.priority:type_name -> notifications.NotificationPriority
	2,  // 37: notifications.CreateTemplateRequest.channels:type_name -> notifications.NotificationChannel
	0,  // 38: notifications.ListTemplatesRequest.type:type_name -> notifications.NotificationType
	7,  // 39: notifications.ListTemplatesResponse.templates:type_name -> notifications.NotificationTemplate
	0,  // 40: notifications.UpdateTemplateRequest.type:type_name -> notifications.NotificationType
	1,  // 41: notifications.UpdateTemplateRequest.priority:type_name -> notifications.NotificationPriority
	2,  // 42: notifications.UpdateTemplateRequest.channels:type_name -> notifications.NotificationChannel
	0,  // 43: notifications.GetUserPreferencesRequest.type:type_name -> notifications.NotificationType
	0,  // 44: notifications.UpdateUserPreferencesRequest.type:type_name -> notifications.NotificationType
	2,  // 45: notifications.UpdateUserPreferencesRequest.channels:type_name -> notifications.NotificationChannel
	9,  // 46: notifications.UpdateUserPreferencesRequest.schedule:type_name -> notifications.NotificationSchedule
	32, // 47: notifications.GetNotificationStatsRequest.start_time:type_name -> google.protobuf.Timestamp
	32, // 48: notifications.GetNotificationStatsRequest.end_time:type_name -> google.protobuf.Timestamp
	0,  // 49: notifications.GetNotificationStatsRequest.type:type_name -> notifications.NotificationType
	4,  // 50: notifications.NotificationsService.Health:input_type -> notifications.HealthRequest
	11, // 51: notifications.NotificationsService.DispatchNotification:input_type -> notifications.DispatchNotificationRequest
	13, // 52: notifications.NotificationsService.GetNotification:input_type -> notifications.GetNotificationRequest
	14, // 53: notifications.NotificationsService.ListNotifications:input_type -> notifications.ListNotificationsRequest
	16, // 54: notifications.NotificationsService.UpdateNotificationStatus:input_type -> notifications.UpdateNotificationStatusRequest
	17, // 55: notifications.NotificationsService.CreateTemplate:input_type -> notifications.CreateTemplateRequest
	18, // 56: notifications.NotificationsService.GetTemplate:input_type -> notifications.GetTemplateRequest
	19, // 57: notifications.NotificationsService.ListTemplates:input_type -> notifications.ListTemplatesRequest
	21, // 58: notifications.NotificationsService.UpdateTemplate:input_type -> notifications.UpdateTemplateRequest
	22, // 59: notifications.NotificationsService.DeleteTemplate:input_type -> notifications.DeleteTemplateRequest
	24, // 60: notifications.NotificationsService.GetUserPreferences:input_type -> notifications.GetUserPreferencesRequest
	25, // 61: notifications.NotificationsService.UpdateUserPreferences:input_type -> notifications.UpdateUserPreferencesRequest
	26, // 62: notifications.NotificationsService.GetNotificationStats:input_type -> notifications.GetNotificationStatsRequest
	5,  // 63: notifications.NotificationsService.Health:output_type -> notifications.HealthResponse
	12, // 64: notifications.NotificationsService.DispatchNotification:output_type -> notifications.DispatchNotificationResponse
	6,  // 65: notifications.NotificationsService.GetNotification:output_type -> notifications.Notification
	15, // 66: notifications.NotificationsService.ListNotifications:output_type -> notifications.ListNotificationsResponse
	6,  // 67: notifications.NotificationsService.UpdateNotificationStatus:output_type -> notifications.Notification
	7,  // 68: notifications.NotificationsService.CreateTemplate:output_type -> notifications.NotificationTemplate
	7,  // 69: notifications.NotificationsService.GetTemplate:output_type -> notifications.NotificationTemplate
	20, // 70: notifications.NotificationsService.ListTemplates:output_type -> notifications.ListTemplatesResponse
	7,  // 71: notifications.NotificationsService.UpdateTemplate:output_type -> notifications.NotificationTemplate
	23, // 72: notifications.NotificationsService.DeleteTemplate:output_type -> notifications.DeleteTemplateResponse
	8,  // 73: notifications.NotificationsService.GetUserPreferences:output_type -> notifications.NotificationPreference
	8,  // 74: notifications.NotificationsService.UpdateUserPreferences:output_type -> notifications.NotificationPreference
	10, // 75: notifications.NotificationsService.GetNotificationStats:output_type -> notifications.NotificationStats
	63, // [63:76] is the sub-list for method output_type
	50, // [50:63] is the sub-list for method input_type
	50, // [50:50] is the sub-list for extension type_name
	50, // [50:50] is the sub-list for extension extendee
	0,  // [0:50] is the sub-list for field type_name
}

func init() { file_api_proto_notifications_notifications_proto_init() }
func file_api_proto_notifications_notifications_proto_init() {
	if File_api_proto_notifications_notifications_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_notifications_notifications_proto_rawDesc), len(file_api_proto_notifications_notifications_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_notifications_notifications_proto_goTypes,
		DependencyIndexes: file_api_proto_notifications_notifications_proto_depIdxs,
		EnumInfos:         file_api_proto_notifications_notifications_proto_enumTypes,
		MessageInfos:      file_api_proto_notifications_notifications_proto_msgTypes,
	}.Build()
	File_api_proto_notifications_notifications_proto = out.File
	file_api_proto_notifications_notifications_proto_goTypes = nil
	file_api_proto_notifications_notifications_proto_depIdxs = nil
}
