version: "3"

vars:
  SERVICES: gateway auth vpn-core dpi-bypass server-manager analytics notifications

tasks:
  # Основные команды
  dev:
    desc: Запуск всех сервисов с hot reload
    cmds: ["task dev:all"]
  build:
    desc: Сборка всех сервисов
    cmds: ["task build:all"]
  test:
    desc: Запуск всех тестов
    cmds: ["task test:all"]
  clean:
    desc: Очистка всех артефактов
    cmds: ["task clean:all"]

  # Запуск всех сервисов в dev режиме
  dev:all:
    desc: Запуск всех сервисов с hot reload
    deps: [deps, configs]
    cmds:
      - task: dev:gateway
      - task: dev:auth
      - task: dev:vpn-core
      - task: dev:dpi-bypass
      - task: dev:server-manager
      - task: dev:analytics
      - task: dev:notifications

  # Запуск отдельных сервисов
  dev:gateway:
    desc: Запуск Gateway с hot reload
    dir: api/gateway
    cmds: [air]

  dev:auth:
    desc: Запуск Auth с hot reload
    dir: api/auth
    cmds: [air]

  dev:vpn-core:
    desc: Запуск VPN Core с hot reload
    dir: rpc/vpn-core
    cmds: [air]

  dev:dpi-bypass:
    desc: Запуск DPI Bypass с hot reload
    dir: rpc/dpi-bypass
    cmds: [air]

  dev:server-manager:
    desc: Запуск Server Manager с hot reload
    dir: rpc/server-manager
    cmds: [air]

  dev:analytics:
    desc: Запуск Analytics с hot reload
    dir: rpc/analytics
    cmds: [air]

  dev:notifications:
    desc: Запуск Notifications с hot reload
    dir: rpc/notifications
    cmds: [air]

  # Сборка
  build:all:
    desc: Сборка всех сервисов
    cmds:
      - task: build:gateway
      - task: build:auth
      - task: build:vpn-core
      - task: build:dpi-bypass
      - task: build:server-manager
      - task: build:analytics
      - task: build:notifications

  build:gateway:
    desc: Сборка Gateway
    dir: api/gateway
    cmds: [go build -o bin/gateway ./cmd]

  build:auth:
    desc: Сборка Auth
    dir: api/auth
    cmds: [go build -o bin/auth ./cmd]

  build:vpn-core:
    desc: Сборка VPN Core
    dir: rpc/vpn-core
    deps: [proto:generate]
    cmds: [go build -o bin/vpn-core ./cmd]

  build:dpi-bypass:
    desc: Сборка DPI Bypass
    dir: rpc/dpi-bypass
    cmds: [go build -o bin/dpi-bypass ./cmd]

  build:server-manager:
    desc: Сборка Server Manager
    dir: rpc/server-manager
    cmds: [go build -o bin/server-manager ./cmd]

  build:analytics:
    desc: Сборка Analytics
    dir: rpc/analytics
    cmds: [go build -o bin/analytics ./cmd]

  build:notifications:
    desc: Сборка Notifications
    dir: rpc/notifications
    cmds: [go build -o bin/notifications ./cmd]

  # Тестирование
  test:all:
    desc: Запуск всех тестов
    cmds:
      - task: test:gateway
      - task: test:auth
      - task: test:vpn-core
      - task: test:dpi-bypass
      - task: test:server-manager
      - task: test:analytics
      - task: test:notifications

  test:gateway:
    desc: Тесты Gateway
    dir: api/gateway
    cmds: [go test ./...]

  test:auth:
    desc: Тесты Auth
    dir: api/auth
    cmds:
      - go test ./internal/adapters/database
      - go test ./internal/adapters/http
      - go test ./internal/services

  test:vpn-core:
    desc: Тесты VPN Core
    dir: rpc/vpn-core
    cmds: [go test ./...]

  test:dpi-bypass:
    desc: Тесты DPI Bypass
    dir: rpc/dpi-bypass
    cmds: [go test ./...]

  test:server-manager:
    desc: Тесты Server Manager
    dir: rpc/server-manager
    cmds: [go test ./...]

  test:analytics:
    desc: Тесты Analytics
    dir: rpc/analytics
    cmds: [go test ./...]

  test:notifications:
    desc: Тесты Notifications
    dir: rpc/notifications
    cmds: [go test ./...]

  # Очистка
  clean:all:
    desc: Очистка всех артефактов
    cmds:
      - find . -name "tmp" -type d -exec rm -rf {} + 2>/dev/null || true
      - find . -name "bin" -type d -exec rm -rf {} + 2>/dev/null || true
      - find . -name "build-errors.log" -delete 2>/dev/null || true

  # Утилиты
  deps:
    desc: Установка зависимостей
    cmds: [go work sync]

  proto:generate:
    desc: Генерация gRPC кода из proto файлов
    dir: rpc/vpn-core
    cmds: [./scripts/generate.sh]

  configs:
    desc: Создание конфигурационных файлов
    cmds:
      - mkdir -p api/gateway/etc api/auth/etc rpc/vpn-core/etc rpc/dpi-bypass/etc rpc/server-manager/etc rpc/analytics/etc rpc/notifications/etc
      - echo "Созданы директории для конфигов"

  logs:
    desc: Просмотр логов всех сервисов
    cmds:
      - echo "Логи Gateway:"
      - tail -f api/gateway/build-errors.log &
      - echo "Логи Auth:"
      - tail -f api/auth/build-errors.log &
      - echo "Логи VPN Core:"
      - tail -f rpc/vpn-core/build-errors.log &
      - wait

  # Docker
  docker:build:
    desc: Сборка Docker образов
    cmds: [docker-compose build]

  docker:up:
    desc: Запуск Docker контейнеров
    cmds: [docker-compose up -d]

  docker:down:
    desc: Остановка Docker контейнеров
    cmds: [docker-compose down]

  # Помощь
  help:
    desc: Показать справку
    cmds:
      - echo "Доступные команды:"
      - echo "  task dev          - Запуск всех сервисов с hot reload"
      - echo "  task dev:gateway  - Запуск только Gateway"
      - echo "  task build        - Сборка всех сервисов"
      - echo "  task test         - Запуск всех тестов"
      - echo "  task clean        - Очистка артефактов"
      - echo "  task deps         - Установка зависимостей"
      - echo "  task docker:up    - Запуск Docker контейнеров"
      - echo "  task help         - Эта справка"
  lint:auth:
    desc: Линтинг Auth
    dir: api/auth
    cmds: [golangci-lint run]

  lint:vpn-core:
    desc: Линтинг VPN Core
    dir: rpc/vpn-core
    cmds: [golangci-lint run]

  lint:dpi-bypass:
    desc: Линтинг DPI Bypass
    dir: rpc/dpi-bypass
    cmds: [golangci-lint run]

  lint:server-manager:
    desc: Линтинг Server Manager
    dir: rpc/server-manager
    cmds: [golangci-lint run]

  lint:analytics:
    desc: Линтинг Analytics
    dir: rpc/analytics
    cmds: [golangci-lint run]

  lint:notifications:
    desc: Линтинг Notifications
    dir: rpc/notifications
    cmds: [golangci-lint run]

  lint:
    desc: Линтинг всех сервисов
    cmds:
      - task: lint:auth
      - task: lint:vpn-core
      - task: lint:dpi-bypass
      - task: lint:server-manager
      - task: lint:analytics
      - task: lint:notifications
