root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/auth"
  cmd = "go build -o ./tmp/auth ./cmd"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = true
  keep_scroll = true

[env]
  HTTP_PORT = "8081"
  GRPC_PORT = "9081"
  DB_HOST = "localhost"
  DB_PORT = "5432"
  DB_USER = "postgres"
  DB_PASSWORD = "password"
  DB_NAME = "silence_auth"
  DB_SSLMODE = "disable"
  REDIS_HOST = "localhost"
  REDIS_PORT = "6379"
  JWT_SECRET = "development-jwt-secret-key-change-this-in-production"
  JWT_EXPIRATION = "24h"
  JWT_REFRESH_EXPIRATION = "168h"
  BCRYPT_COST = "12"
  INTERNAL_API_TOKEN = "super-secret-internal-token"
  RATE_LIMIT_REQUESTS = "100"
  RATE_LIMIT_WINDOW = "1m"
  MIGRATIONS_DIR = "internal/adapters/database/migrations"
  LOG_LEVEL = "info"
  LOG_FORMAT = "json"
  VERSION = "1.0.0"
