apiVersion: v1
kind: ConfigMap
metadata:
  name: silence-config
  namespace: silence
  labels:
    app: silence-vpn
    component: config
data:
  # Database configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "silence_db"
  DB_SSLMODE: "disable"

  # Redis configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"

  # RabbitMQ configuration
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "admin"
  RABBITMQ_VHOST: "/"
  RABBITMQ_EXCHANGE: "notifications"
  RABBITMQ_QUEUE: "notifications_queue"
  RABBITMQ_ROUTING_KEY: "notifications.*"
  RABBITMQ_CONSUMER_TAG: "notifications_consumer"
  RABBITMQ_PREFETCH_COUNT: "10"

  # InfluxDB configuration
  INFLUXDB_URL: "http://influxdb-service:8086"
  INFLUXDB_ORG: "silence"
  INFLUXDB_BUCKET: "analytics"

  # ClickHouse configuration
  CLICKHOUSE_HOST: "clickhouse-service"
  CLICKHOUSE_PORT: "9000"
  CLICKHOUSE_DB: "silence_analytics"
  CLICKHOUSE_USER: "admin"

  # Service ports
  HTTP_PORT: "8080"
  GRPC_PORT: "9080"

  # JWT configuration
  JWT_EXPIRATION: "24h"
  JWT_REFRESH_EXPIRATION: "168h"
  BCRYPT_COST: "12"

  # Rate limiting
  RATE_LIMIT_REQUESTS: "100"
  RATE_LIMIT_WINDOW: "1m"

  # Logging
  LOG_LEVEL: "info"

  # Docker configuration
  DOCKER_API_VERSION: "1.41"
  DOCKER_TIMEOUT: "30s"

  # Migrations
  MIGRATIONS_DIR: "/app/migrations"

  # Application version
  VERSION: "1.0.0"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: silence-monitoring-config
  namespace: silence-monitoring
  labels:
    app: silence-vpn
    component: monitoring
data:
  # Prometheus configuration
  PROMETHEUS_RETENTION: "200h"
  PROMETHEUS_STORAGE_PATH: "/prometheus"

  # Grafana configuration
  GF_SECURITY_ADMIN_PASSWORD: "admin"
  GF_USERS_ALLOW_SIGN_UP: "false"

  # Jaeger configuration
  COLLECTOR_OTLP_ENABLED: "true"
  COLLECTOR_ZIPKIN_HOST_PORT: ":9411"

  # Loki configuration
  LOKI_STORAGE_PATH: "/loki"

  # AlertManager configuration
  ALERTMANAGER_STORAGE_PATH: "/alertmanager"
