apiVersion: v1
kind: Secret
metadata:
  name: silence-secrets
  namespace: silence
  labels:
    app: silence-vpn
    component: secrets
type: Opaque
data:
  # Database passwords (base64 encoded)
  DB_PASSWORD: cGFzc3dvcmQ=  # password

  # Redis password (if needed)
  REDIS_PASSWORD: ""

  # RabbitMQ credentials
  RABBITMQ_PASSWORD: YWRtaW4=  # admin

  # InfluxDB credentials
  INFLUXDB_PASSWORD: YWRtaW5wYXNzd29yZA==  # adminpassword
  INFLUXDB_TOKEN: eW91ci1pbmZsdXhkYi10b2tlbg==  # your-influxdb-token

  # ClickHouse credentials
  CLICKHOUSE_PASSWORD: cGFzc3dvcmQ=  # password

  # JWT secrets
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9u  # your-jwt-secret-key-change-this-in-production

  # Internal API token
  INTERNAL_API_TOKEN: c3VwZXItc2VjcmV0LWludGVybmFsLXRva2Vu  # super-secret-internal-token

---
apiVersion: v1
kind: Secret
metadata:
  name: silence-monitoring-secrets
  namespace: silence-monitoring
  labels:
    app: silence-vpn
    component: monitoring
type: Opaque
data:
  # Grafana admin password
  GF_SECURITY_ADMIN_PASSWORD: YWRtaW4=  # admin

  # AlertManager webhook tokens (if needed)
  ALERTMANAGER_WEBHOOK_TOKEN: ""

  # Slack/Discord webhook URLs (if needed)
  SLACK_WEBHOOK_URL: ""
  DISCORD_WEBHOOK_URL: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: silence
  labels:
    app: silence-vpn
    component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6e319  # Empty docker config for local registry
