apiVersion: v1
kind: PersistentVolume
metadata:
  name: silence-postgres-pv
  namespace: silence
  labels:
    app.kubernetes.io/name: silence
    app.kubernetes.io/instance: silence
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: postgres
    app.kubernetes.io/part-of: silence
    app.kubernetes.io/managed-by: kubernetes
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/silence/postgres
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - silence-node

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: silence-postgres-pvc
  namespace: silence
  labels:
    app.kubernetes.io/name: silence
    app.kubernetes.io/instance: silence
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: postgres
    app.kubernetes.io/part-of: silence
    app.kubernetes.io/managed-by: kubernetes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      app.kubernetes.io/component: postgres

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: silence-redis-pv
  namespace: silence
  labels:
    app.kubernetes.io/name: silence
    app.kubernetes.io/instance: silence
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: silence
    app.kubernetes.io/managed-by: kubernetes
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/silence/redis
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - silence-node

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: silence-redis-pvc
  namespace: silence
  labels:
    app.kubernetes.io/name: silence
    app.kubernetes.io/instance: silence
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: silence
    app.kubernetes.io/managed-by: kubernetes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      app.kubernetes.io/component: redis

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: silence-influxdb-pv
  namespace: silence
  labels:
    app.kubernetes.io/name: silence
    app.kubernetes.io/instance: silence
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: influxdb
    app.kubernetes.io/part-of: silence
    app.kubernetes.io/managed-by: kubernetes
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/silence/influxdb
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - silence-node

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: silence-influxdb-pvc
  namespace: silence
  labels:
    app.kubernetes.io/name: silence
    app.kubernetes.io/instance: silence
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: influxdb
    app.kubernetes.io/part-of: silence
    app.kubernetes.io/managed-by: kubernetes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      app.kubernetes.io/component: influxdb

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: silence-clickhouse-pv
  namespace: silence
  labels:
    app.kubernetes.io/name: silence
    app.kubernetes.io/instance: silence
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: clickhouse
    app.kubernetes.io/part-of: silence
    app.kubernetes.io/managed-by: kubernetes
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/silence/clickhouse
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - silence-node

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: silence-clickhouse-pvc
  namespace: silence
  labels:
    app.kubernetes.io/name: silence
    app.kubernetes.io/instance: silence
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: clickhouse
    app.kubernetes.io/part-of: silence
    app.kubernetes.io/managed-by: kubernetes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      app.kubernetes.io/component: clickhouse

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: silence-rabbitmq-pv
  namespace: silence
  labels:
    app.kubernetes.io/name: silence
    app.kubernetes.io/instance: silence
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/part-of: silence
    app.kubernetes.io/managed-by: kubernetes
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/silence/rabbitmq
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - silence-node

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: silence-rabbitmq-pvc
  namespace: silence
  labels:
    app.kubernetes.io/name: silence
    app.kubernetes.io/instance: silence
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/part-of: silence
    app.kubernetes.io/managed-by: kubernetes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      app.kubernetes.io/component: rabbitmq

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: silence-prometheus-pv
  namespace: silence
  labels:
    app.kubernetes.io/name: silence
    app.kubernetes.io/instance: silence
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: silence
    app.kubernetes.io/managed-by: kubernetes
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/silence/prometheus
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - silence-node

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: silence-prometheus-pvc
  namespace: silence
  labels:
    app.kubernetes.io/name: silence
    app.kubernetes.io/instance: silence
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: silence
    app.kubernetes.io/managed-by: kubernetes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      app.kubernetes.io/component: prometheus

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: silence-grafana-pv
  namespace: silence
  labels:
    app.kubernetes.io/name: silence
    app.kubernetes.io/instance: silence
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: silence
    app.kubernetes.io/managed-by: kubernetes
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/silence/grafana
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - silence-node

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: silence-grafana-pvc
  namespace: silence
  labels:
    app.kubernetes.io/name: silence
    app.kubernetes.io/instance: silence
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: silence
    app.kubernetes.io/managed-by: kubernetes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      app.kubernetes.io/component: grafana

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: silence-loki-pv
  namespace: silence
  labels:
    app.kubernetes.io/name: silence
    app.kubernetes.io/instance: silence
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: loki
    app.kubernetes.io/part-of: silence
    app.kubernetes.io/managed-by: kubernetes
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/silence/loki
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - silence-node

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: silence-loki-pvc
  namespace: silence
  labels:
    app.kubernetes.io/name: silence
    app.kubernetes.io/instance: silence
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: loki
    app.kubernetes.io/part-of: silence
    app.kubernetes.io/managed-by: kubernetes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      app.kubernetes.io/component: loki

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: silence-jaeger-pv
  namespace: silence
  labels:
    app.kubernetes.io/name: silence
    app.kubernetes.io/instance: silence
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: jaeger
    app.kubernetes.io/part-of: silence
    app.kubernetes.io/managed-by: kubernetes
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/silence/jaeger
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - silence-node

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: silence-jaeger-pvc
  namespace: silence
  labels:
    app.kubernetes.io/name: silence
    app.kubernetes.io/instance: silence
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: jaeger
    app.kubernetes.io/part-of: silence
    app.kubernetes.io/managed-by: kubernetes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      app.kubernetes.io/component: jaeger

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  namespace: silence
  labels:
    app.kubernetes.io/name: silence
    app.kubernetes.io/instance: silence
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: silence
    app.kubernetes.io/managed-by: kubernetes
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
