apiVersion: v1
kind: Secret
metadata:
  name: silence-secrets
  namespace: silence
  labels:
    app.kubernetes.io/name: silence
    app.kubernetes.io/instance: silence
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: silence
    app.kubernetes.io/managed-by: kubernetes
type: Opaque
data:
  # Database passwords (base64 encoded)
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # password
  CLICKHOUSE_PASSWORD: cGFzc3dvcmQ=  # password

  # Redis password (empty by default)
  REDIS_PASSWORD: ""

  # RabbitMQ password
  RABBITMQ_DEFAULT_PASS: YWRtaW4=  # admin

  # InfluxDB token
  INFLUXDB_TOKEN: eW91ci1pbmZsdXhkYi10b2tlbg==  # your-influxdb-token
  ANALYTICS_INFLUXDB_TOKEN: eW91ci1pbmZsdXhkYi10b2tlbg==  # your-influxdb-token

  # JWT secrets
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9u  # your-jwt-secret-key-change-this-in-production

  # Internal API tokens
  INTERNAL_API_TOKEN: c3VwZXItc2VjcmV0LWludGVybmFsLXRva2Vu  # super-secret-internal-token

  # TLS certificates (if needed)
  TLS_CERT: ""
  TLS_KEY: ""

  # Additional service-specific secrets
  AUTH_ENCRYPTION_KEY: YXV0aC1lbmNyeXB0aW9uLWtleS0zMi1ieXRlcw==  # auth-encryption-key-32-bytes
  SESSION_SECRET: c2Vzc2lvbi1zZWNyZXQta2V5LWZvci1jb29raWVz  # session-secret-key-for-cookies

  # Notification service secrets
  NOTIFICATION_WEBHOOK_SECRET: bm90aWZpY2F0aW9uLXdlYmhvb2stc2VjcmV0  # notification-webhook-secret

  # VPN service secrets
  VPN_PRIVATE_KEY: dnBuLXByaXZhdGUta2V5LWZvci1lbmNyeXB0aW9u  # vpn-private-key-for-encryption

  # Analytics service secrets
  ANALYTICS_API_KEY: YW5hbHl0aWNzLWFwaS1rZXktZm9yLWV4dGVybmFs  # analytics-api-key-for-external
