server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: silence-analytics
    static_configs:
      - targets:
          - localhost
        labels:
          job: silence-analytics
          service: analytics
          __path__: /var/log/silence/analytics/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service: service.name
            message: message
            trace_id: trace_id
            span_id: span_id
            user_id: user_id
            server_id: server_id
            region: region
            error_type: error_type
      - labels:
          level:
          service:
          trace_id:
          span_id:
          user_id:
          server_id:
          region:
          error_type:
      - timestamp:
          source: timestamp
          format: RFC3339
      - output:
          source: message

  - job_name: silence-gateway
    static_configs:
      - targets:
          - localhost
        labels:
          job: silence-gateway
          service: gateway
          __path__: /var/log/silence/gateway/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service: service.name
            message: message
            trace_id: trace_id
            span_id: span_id
            user_id: user_id
            method: http.method
            endpoint: http.endpoint
            status_code: http.status_code
      - labels:
          level:
          service:
          trace_id:
          span_id:
          user_id:
          method:
          endpoint:
          status_code:
      - timestamp:
          source: timestamp
          format: RFC3339
      - output:
          source: message

  - job_name: silence-vpn-core
    static_configs:
      - targets:
          - localhost
        labels:
          job: silence-vpn-core
          service: vpn-core
          __path__: /var/log/silence/vpn-core/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service: service.name
            message: message
            trace_id: trace_id
            span_id: span_id
            user_id: user_id
            server_id: server_id
            region: region
            connection_id: connection_id
      - labels:
          level:
          service:
          trace_id:
          span_id:
          user_id:
          server_id:
          region:
          connection_id:
      - timestamp:
          source: timestamp
          format: RFC3339
      - output:
          source: message

  - job_name: silence-dpi-bypass
    static_configs:
      - targets:
          - localhost
        labels:
          job: silence-dpi-bypass
          service: dpi-bypass
          __path__: /var/log/silence/dpi-bypass/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service: service.name
            message: message
            trace_id: trace_id
            span_id: span_id
            user_id: user_id
            server_id: server_id
            region: region
            bypass_type: bypass_type
      - labels:
          level:
          service:
          trace_id:
          span_id:
          user_id:
          server_id:
          region:
          bypass_type:
      - timestamp:
          source: timestamp
          format: RFC3339
      - output:
          source: message

  - job_name: silence-server-manager
    static_configs:
      - targets:
          - localhost
        labels:
          job: silence-server-manager
          service: server-manager
          __path__: /var/log/silence/server-manager/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service: service.name
            message: message
            trace_id: trace_id
            span_id: span_id
            server_id: server_id
            region: region
            operation: operation
      - labels:
          level:
          service:
          trace_id:
          span_id:
          server_id:
          region:
          operation:
      - timestamp:
          source: timestamp
          format: RFC3339
      - output:
          source: message

  - job_name: silence-notifications
    static_configs:
      - targets:
          - localhost
        labels:
          job: silence-notifications
          service: notifications
          __path__: /var/log/silence/notifications/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service: service.name
            message: message
            trace_id: trace_id
            span_id: span_id
            user_id: user_id
            notification_type: notification_type
      - labels:
          level:
          service:
          trace_id:
          span_id:
          user_id:
          notification_type:
      - timestamp:
          source: timestamp
          format: RFC3339
      - output:
          source: message

  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container_name"
      - source_labels:
          ["__meta_docker_container_label_com_docker_compose_service"]
        target_label: "service"
      - source_labels:
          ["__meta_docker_container_label_com_docker_compose_project"]
        target_label: "project"
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service: service.name
            message: message
            trace_id: trace_id
            span_id: span_id
      - labels:
          level:
          service:
          trace_id:
          span_id:
      - timestamp:
          source: timestamp
          format: RFC3339
          fallback_formats:
            - RFC3339Nano
            - "2006-01-02T15:04:05.000Z07:00"
            - "2006-01-02T15:04:05Z07:00"
      - output:
          source: message

  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:1514
      idle_timeout: 60s
      label_structured_data: true
      labels:
        job: "syslog"
    relabel_configs:
      - source_labels: ["__syslog_message_hostname"]
        target_label: "host"
      - source_labels: ["__syslog_message_severity"]
        target_label: "level"
      - source_labels: ["__syslog_message_app_name"]
        target_label: "service"
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}Z)\s+(?P<level>\w+)\s+(?P<service>\w+)\s+(?P<message>.*)$'
      - labels:
          level:
          service:
      - timestamp:
          source: timestamp
          format: RFC3339
      - output:
          source: message

  - job_name: journal
    journal:
      max_age: 12h
      labels:
        job: "systemd-journal"
    relabel_configs:
      - source_labels: ["__journal__systemd_unit"]
        target_label: "unit"
      - source_labels: ["__journal__hostname"]
        target_label: "host"
      - source_labels: ["__journal_priority"]
        target_label: "level"
    pipeline_stages:
      - json:
          expressions:
            timestamp: __journal__realtime_timestamp
            level: __journal_priority
            message: __journal_message
            unit: __journal__systemd_unit
      - labels:
          level:
          unit:
      - timestamp:
          source: timestamp
          format: Unix
      - output:
          source: message

limits_config:
  readline_rate: 10000
  readline_burst: 20000
  max_streams: 0
  max_line_size: 0
  max_line_size_truncate: false

target_config:
  sync_period: 10s
